---
name: Called Workflow - Accessibility Test

on:
  workflow_call:
    inputs:
      ACCESSIBILITY_URL:
        required: true
        type: string

jobs:
  run-sitespeed:
    runs-on: ubuntu-latest
    name: Accessibility Test
    steps:
      - uses: actions/checkout@v2

      - name: Install Pa11y
        run: npm install -g pa11y

      - name: Run Test
        run: pa11y ${{ inputs.ACCESSIBILITY_URL }} > accessibility.json

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: accessibility-result
          path: accessibility.json
          retention-days: 5