---
name: Called Workflow - Container Image Scan

on:
  workflow_call:
    inputs:
      IMAGE:
        required: false
        type: string

jobs:
  container_scan:
    name: Container Image Scan
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v2
        with:
          name: build.env
          path: .

      - name: Set Next Release Vars
        run: |
          cat ./build.env
          echo "nextReleaseVersion=$(cat build.env | cut -f2 -d"=")" >> $GITHUB_ENV

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ inputs.IMAGE }}:${{ env.nextReleaseVersion }}'
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'