---
name: Called Workflow - Container Image Scan

on:
  workflow_call:
    inputs:
      IMAGE:
        required: false
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_REGION:
        required: true

jobs:
  container_scan:
    name: Container Image Scan
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v2
        with:
          name: build.env
          path: .

      - name: Set Next Release Vars
        run: |
          cat ./build.env
          echo "nextReleaseVersion=$(cat build.env | cut -f2 -d"=")" >> $GITHUB_ENV

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          mask-aws-account-id: "no"

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ inputs.IMAGE }}:${{ env.nextReleaseVersion }}'
          format: 'json'
          output: 'container-scanning-report.json'

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: container-scanning-report.json
          path: container-scanning-report.json
          retention-days: 5