---
name: Called Workflow - Get Version

on:
  workflow_call:
    inputs:
      RELEASE_BRANCH:
        required: false
        type: string
    secrets:
      envPAT:
        required: false

jobs:
  get_version:
    name: Get Version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.envPAT }}
          # NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm install -g semantic-release @semantic-release/git @semantic-release/exec
          semantic-release --branches ${{ inputs.RELEASE_BRANCH }} --dry-run

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: build.env
          path: build.env
          retention-days: 5
