---
name: Called Workflow - Prepare

on:
  workflow_call:
    inputs:
      CHART_PATH:
        required: true
        type: string
      BACKEND_VALUES_FILE:
        required: true
        type: string
      FRONTEND_VALUES_FILE:
        required: true
        type: string

jobs:
  linting:
    name: Prepare
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3

      # Set up Python
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Helm Lint
        run: |
          helm lint ${{ inputs.CHART_PATH }} --values ${{ inputs.BACKEND_VALUES_FILE }}
          helm lint ${{ inputs.CHART_PATH }} --values ${{ inputs.FRONTEND_VALUES_FILE }}

      - name: Yaml Lint
        run: |
          yamllint .
      
      - name: App Lint
        continue-on-error: true
        run: |
          npm i next eslint
          pushd frontend && npm run lint; popd
          pushd backend  && npm run lint; popd
