---
name: Called Workflow - Prepare

on:
  workflow_call:
    inputs:
      CHART_PATH:
        required: true
        type: string
      BACKEND_VALUES_FILE:
        required: true
        type: string
      FRONTEND_VALUES_FILE:
        required: true
        type: string

jobs:
  linting:
    name: Prepare
    runs-on: ubuntu-latest
    timeout-minutes: 5
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3

      # Set up Python
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Helm Lint
        run: |
          helm lint ${{ inputs.CHART_PATH }} --values ${{ inputs.BACKEND_VALUES_FILE }}
          helm lint ${{ inputs.CHART_PATH }} --values ${{ inputs.FRONTEND_VALUES_FILE }}

      - name: Yaml Lint
        run: |
          yamllint .
      
      - name: App Lint
        continue-on-error: true
        run: |
          npm i eslint-config-next next
          pushd frontend && npm run lint; popd
          pushd backend  && npm run lint; popd

      - name: Audit App Deps
        continue-on-error: true
        run: |
          python3 -m pip install requests
          cd backend && npm audit --json > npm_audit_backend.json || exit_code=$?
          cd ../frontend && npm audit --json > npm_audit_frontend.json || exit_code=$?
          python3 ../importtodefectdojo.py ../backend/npm_audit_backend.json 'NPM Audit Scan'
          python3 ../importtodefectdojo.py npm_audit_frontend.json 'NPM Audit Scan'
      
      - name: 'Upload Artifact 1'
        uses: actions/upload-artifact@v3
        with:
          name: npm_audit_backend.json
          path: npm_audit_backend.json
          retention-days: 5

      - name: 'Upload Artifact 2'
        uses: actions/upload-artifact@v3
        with:
          name: npm_audit_frontend.json
          path: npm_audit_frontend.json
          retention-days: 5
