---
name: Called Workflow - UI Performance

on:
  workflow_call:

jobs:
  run-sitespeed:
    runs-on: ubuntu-latest
    name: UI Performance
    steps:
      - uses: actions/checkout@v2

      - name: Run sitespeed.io container with arguments and optional Docker options
        run: docker run -v "$(pwd):/sitespeed.io" sitespeedio/sitespeed.io:25.11.0 https://www.sitespeed.io --outputFolder sitespeed-result https://konomo-test.hack.cloudnative.nttdatauk.cloud/ -b chrome

      - name: Move Result
        run: mv /sitespeed.io/sitespeed-result/data/performance.json browser-performance.json

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: browser-performance.json
          path: browser-performance.json
          retention-days: 5