---
name: Called Workflow - UI Performance

on:
  workflow_call:
    inputs:
      PERFORMANCE_URL:
        required: true
        type: string

jobs:
  run-sitespeed:
    runs-on: ubuntu-latest
    name: UI Performance
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2

      - name: Run sitespeed.io container with arguments and optional Docker options
        run: docker run -v "$(pwd):/sitespeed.io" sitespeedio/sitespeed.io:25.11.0 https://www.sitespeed.io --outputFolder sitespeed-result ${{ inputs.PERFORMANCE_URL }} -b chrome

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: sitespeed-result
          path: sitespeed-result/*
          retention-days: 5